### ISSUE TITLE
Symfony 3.0 Compatible?

### ISSUE THREAD

**Issue by richardfullmer** [idr0id/Papper#11]
Great library.

We're upgrading to SF3 locally and this dependency prevents composer from using symfony 3.0:

``` json
"symfony/property-access": "~2.4"
```

Is it possible to losen this restriction to `~2.4|^3.0`?  If this library isn't using any deprecated API's in `symfony/property-access` then everything should work fine.

**Comment by idr0id** [comment]
Thanks for issue!
I change `property-access` version restriction to `~2.4|^3.0` and release `1.1.2`.
